# Generated by Django 3.1.7 on 2021-04-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalcAerConc',
            fields=[
                ('aer_conc_cd', models.AutoField(primary_key=True, serialize=False)),
                ('aer_conc_nm', models.CharField(max_length=255)),
                ('cvalue', models.FloatField(blank=True, null=True)),
                ('use_yn', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'calc_aer_conc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalcAreaGb',
            fields=[
                ('area_gb_cd', models.AutoField(primary_key=True, serialize=False)),
                ('area_gb_nm', models.CharField(max_length=255)),
                ('use_yn', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'calc_area_gb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalcExFinm',
            fields=[
                ('ex_finm_cd', models.AutoField(primary_key=True, serialize=False)),
                ('ex_finm_nm', models.CharField(max_length=255)),
                ('cvalue', models.FloatField(blank=True, null=True)),
                ('use_yn', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'calc_ex_finm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalcInsulm',
            fields=[
                ('insulm_cd', models.AutoField(primary_key=True, serialize=False)),
                ('insulm_nm', models.CharField(max_length=255)),
                ('cvalue', models.FloatField(blank=True, null=True)),
                ('use_yn', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'calc_insulm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalcLocalgvPoint',
            fields=[
                ('localgv_point_cd', models.AutoField(primary_key=True, serialize=False)),
                ('ex_wall_point', models.FloatField(blank=True, null=True)),
                ('roof_point', models.FloatField(blank=True, null=True)),
                ('floor_point', models.FloatField(blank=True, null=True)),
                ('point_yn', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'calc_localgv_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalcMeanUvalue',
            fields=[
                ('mean_uvalue_cd', models.AutoField(primary_key=True, serialize=False)),
                ('ex_wall', models.FloatField(blank=True, null=True)),
                ('roof', models.FloatField(blank=True, null=True)),
                ('floor', models.FloatField(blank=True, null=True)),
                ('point', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calc_mean_uvalue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalcPart',
            fields=[
                ('part_cd', models.AutoField(primary_key=True, serialize=False)),
                ('part_nm', models.CharField(max_length=255)),
                ('use_yn', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'calc_part',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalcPurps',
            fields=[
                ('purps_cd', models.AutoField(primary_key=True, serialize=False)),
                ('purps_nm', models.CharField(max_length=255)),
                ('use_yn', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'calc_purps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalcSalbRvalue',
            fields=[
                ('slab_rvalue_cd', models.AutoField(primary_key=True, serialize=False)),
                ('direct', models.FloatField(blank=True, null=True)),
                ('indirect', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calc_salb_rvalue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalcSrfcRvalue',
            fields=[
                ('srfc_rvalue_cd', models.AutoField(primary_key=True, serialize=False)),
                ('outdoor', models.FloatField(blank=True, null=True)),
                ('indoor', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calc_srfc_rvalue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalcUvalue',
            fields=[
                ('uvalue_cd', models.AutoField(primary_key=True, serialize=False)),
                ('uvalue', models.FloatField()),
            ],
            options={
                'db_table': 'calc_uvalue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalcUvalueTmpl',
            fields=[
                ('uvalue_tmpl_cd', models.AutoField(primary_key=True, serialize=False)),
                ('wall_direct_kind_1', models.FloatField()),
                ('wall_direct_thick_1', models.FloatField()),
                ('wall_direc_width', models.FloatField()),
                ('wall_indirect_kind_1', models.FloatField()),
                ('wall_indirect_thick_1', models.FloatField()),
                ('wall_indirect_width', models.FloatField()),
                ('wall_direct_kind_2', models.FloatField()),
                ('wall_direct_thick_2', models.FloatField()),
                ('wall_indirect_kind_2', models.FloatField()),
                ('wall_indirect_thick_2', models.FloatField()),
                ('wall_direct_kind_3', models.FloatField()),
                ('wall_direct_thick_3', models.FloatField()),
                ('wall_indirect_kind_3', models.FloatField()),
                ('wall_indirect_thick_3', models.FloatField()),
                ('wall_direct_kind_4', models.FloatField()),
                ('wall_direct_thick_4', models.FloatField()),
                ('wall_indirect_kind_4', models.FloatField()),
                ('wall_indirect_thick_4', models.FloatField()),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('wrt_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calc_uvalue_tmpl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalcWin',
            fields=[
                ('win_cd', models.AutoField(primary_key=True, serialize=False)),
                ('win_nm', models.CharField(max_length=255)),
                ('uvalue', models.FloatField(blank=True, null=True)),
                ('use_yn', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'calc_win',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
    ]
